apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.0
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 301 http://nx-poc-static-martingerlero.s3-website-us-east-1.amazonaws.com;
        }
    }
